// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApi.Models;

namespace MovieApi.Migrations
{
    [DbContext(typeof(MovieApiContext))]
    partial class MovieApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MovieApi.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Genre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("RottenTom")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "Denis Villeneuve",
                            Genre = "Sci-Fi",
                            Name = "Dune",
                            RottenTom = 90,
                            Synopsis = "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence, only those who can conquer their own fear will survive"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "Cloe Zhao",
                            Genre = "Drama",
                            Name = "Nomadland",
                            RottenTom = 82,
                            Synopsis = "A woman embarks on a journey through the American West after losing everything during the recession."
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Walt Becker",
                            Genre = "Kids & Family",
                            Name = "Clifford The Big Red Dog",
                            RottenTom = 94,
                            Synopsis = "When middle-schooler Emily Elizabeth (Darby Camp) meets a magical animal rescuer (John Cleese) who gifts her a little, red puppy, she never anticipated waking up to find a giant ten-foot hound in her small New York City apartment. While her single mom (Sienna Guillory) is away for business, Emily and her fun but impulsive uncle Casey (Jack Whitehall) set out on an adventure that will keep you on the edge-of-your-seat as our heroes take a bite out of the Big Apple. Based on the beloved Scholastic book character, Clifford will teach the world how to love big!"
                        },
                        new
                        {
                            MovieId = 4,
                            Director = "Rian Johnson",
                            Genre = "Darma Mystery",
                            Name = "Knives Out",
                            RottenTom = 92,
                            Synopsis = "Knives Out sharpens old murder-mystery tropes with a keenly assembled suspense outing that makes brilliant use of writer-director Rian Johnson's stellar ensemble"
                        },
                        new
                        {
                            MovieId = 5,
                            Director = "John Krasinski",
                            Genre = "Horror",
                            Name = "A Quiet Place Part II",
                            RottenTom = 92,
                            Synopsis = "Following the deadly events at home, the Abbott family must now face the terrors of the outside world as they continue their fight for survival in silence. Forced to venture into the unknown, they quickly realize that the creatures that hunt by sound are not the only threats that lurk beyond the sand path"
                        },
                        new
                        {
                            MovieId = 6,
                            Director = "Tyler Spindel",
                            Genre = "Comedy",
                            Name = "Father of the Year",
                            RottenTom = 1,
                            Synopsis = "Worst movie ever"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
